server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 169.254.149.130
    username: ego
    password: ego
    virtual-host: /ego
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ego:
  sms:

