server:
  port: 8081
spring:
  application:
    name: item-client
  datasource:
    url: jdbc:mysql://localhost:3306/ego?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 169.254.149.130
    username: ego
    password: ego
    virtual-host: /ego
    template:
      exchange: ego.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl
