server:
  port: 8083
spring:
  application:
    name: search-client
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 169.254.149.130:9300
  jackson:
    default-property-inclusion: non_null  #配置jackson处理时，空值忽略
  rabbitmq:
    host: 169.254.149.130
    username: ego
    password: ego
    virtual-host: /ego
    template:
      exchange: ego.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
