server:
  port: 8085
spring:
  application:
    name: user-client
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ego
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 169.254.149.130
    virtual-host: /ego
    username: ego
    password: ego
    template:
      exchange: ego.sms.exchange
    publisher-confirms: true
  redis:
    host: 169.254.149.130
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.ego.user.pojo
